### PR TITLE
RecortType Support

### PR DESCRIPTION
**Pull request by afaubel**
This is an attempt to add record type support. It includes details of the records types from the source org by adding these to the bundle. Then when the records are de-serialised the code uses the name related to the record type ID to try and find a record type in the destination org. The following is a test used to cover this functionality:

```
    /**
     * @description Test record type support
     **/
    static testMethod void testContactExportRecordType() {

        // Get the record types for the contact object
        Map<String, Id> recordTypeIdMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE sObjectType='Contact']) {
            recordTypeIdMap.put(rt.DeveloperName, rt.Id);
        }

        // Create an account
        Account acc = TestFactory.createAccount('Acc 1');
        insert acc;

        // Create a couple of contacts with different record types
        Map<Integer, Contact> contactMap = new Map<Integer, Contact>();
        Contact contact1 = TestFactory.createContact('Fred', 'Bloggs', acc.Id); 
        contact1.RecordTypeId = recordTypeIdMap.get('DDC_Recruiter');
        contactMap.put(1, contact1);
        Contact contact2 = TestFactory.createContact('Tony', 'Bloggs', acc.Id); 
        contact2.RecordTypeId = recordTypeIdMap.get('Standard');
        contactMap.put(2, contact2);
        insert contactMap.values();

        // Start the test
        Test.startTest();
        
        // Create the JSON data from this test account
        String exportJSON = SObjectDataLoader.serialize(new Set<Id>{contactMap.get(1).Id,contactMap.get(2).Id});
        System.debug('@@@ JSON : ' + exportJSON);        

        // Test the JSON to ensure the correct values are included
        System.assert(exportJSON.contains('Acc 1'));
        System.assert(exportJSON.contains('Fred'));
        System.assert(exportJSON.contains('Tony'));
        System.assert(exportJSON.contains(recordTypeIdMap.get('DDC_Recruiter')));                
        System.assert(exportJSON.contains(recordTypeIdMap.get('Standard')));       
        System.assert(exportJSON.contains('DDC_Recruiter'));
        System.assert(exportJSON.contains('recordTypeMap'));

        // Now replace the ID string for one of the record types and see if that can be imported OK
        String exportJSON2 = exportJSON.replaceAll(recordTypeIdMap.get('DDC_Recruiter'), '012w00000002XXO'); // Just a random Id
        System.debug('@@@ JSON2 : ' + exportJSON2);     

        // Check that the replace has worked
        System.assert(exportJSON2.contains(recordTypeIdMap.get('DDC_Recruiter'))==false);                
        System.assert(exportJSON2.contains(recordTypeIdMap.get('Standard')));       
        System.assert(exportJSON2.contains('012w00000002XXO'));       

        // Delete the two contact records
        delete contactMap.values();

        // Now try and deserialise these records
        Set<Id> newRecordIds = SObjectDataLoader.deserialize(exportJSON2);
        System.assertEquals(1, newRecordIds.size());

        // Stop the test
        Test.stopTest();

        // Get the contacts and test values
        List<Contact> contactList = [SELECT Id, RecordTypeId, FirstName FROM Contact];
        System.assertEquals(2, contactList.size());
        for (Contact c : contactList) {
            if (c.FirstName == 'Fred') {
                System.assertEquals(recordTypeIdMap.get('DDC_Recruiter'), c.RecordTypeId);
            } else if (c.Firstname == 'Tony') {
                System.assertEquals(recordTypeIdMap.get('Standard'), c.RecordTypeId);
            } else {
                System.assert(false, 'Not a valid test record');
            }
        }

    }
```

### CODE REVIEW

**Comment by afawcett** [comment]
@Sonal4J did you make a fix for [this](https://github.com/afaubel/apex-sobjectdataloader/commit/6877a9eafcf7d4ea245a0b0bf04b10fed77d02bc) already, i am not sure?

**Comment by afawcett** [comment]
@afaubel wow this is a major peace of work, thank you so much! Just want to see what @Sonal4J thoughts are on my question above. Otherwise this is looking good!

**Comment by afawcett** [comment]
Also wondering if the RecordType references should use dynamic soql/describe so that this library can still be used in professional edition orgs?

**Comment by Sonal4J** [comment]
@afawcett  I have not made a fix for this

**Comment by afaubel** [comment]
Hi @afawcett that's no problem. All the credit goes to yourself and @Sonal4J. My changes are just tweaks. Good point about the RecordType references and Professional Edition. I'll have a look at that. If there's anything else, please let me know. Thanks again to you both for the sharing the code.

**Comment by afawcett** [comment]
Your very welcome, kind words, i think we should be good after the PE support changes! :+1:

**Pull request merged**
